sudo: required
services:
  - docker

before_install:
  - docker build -t hsedecanter/something-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hsedecanter/something-test npm test

after_success:
  - docker build -t hsedecanter/multi-client ./client
  - docker build -t hsedecanter/multi-nginx ./nginx
  - docker build -t hsedecanter/multi-server ./server
  - docker build -t hsedecanter/multi-worker ./worker
 # log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # take those images and push them to docker hub
  - docker push hsedecanter/multi-client
  - docker push hsedecanter/multi-nginx
  - docker push hsedecanter/multi-server
  - docker push hsedecanter/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: Multidocker-env
    bucket_name: elasticbeanstalk-us-east-2-067160285279
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY